# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: llsm_post_process.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='llsm_post_process.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17llsm_post_process.proto\"%\n\x11\x41vailableServices\x12\x10\n\x08services\x18\x01 \x03(\t\"\x07\n\x05\x45mpty\"\x1a\n\x07NDArray\x12\x0f\n\x07ndarray\x18\x01 \x01(\x0c\x32i\n\x0fLLSMPostProcess\x12\'\n\x07GetList\x12\x06.Empty\x1a\x12.AvailableServices\"\x00\x12-\n\x15GetZStackMaxIntensity\x12\x08.NDArray\x1a\x08.NDArray\"\x00\x62\x06proto3'
)




_AVAILABLESERVICES = _descriptor.Descriptor(
  name='AvailableServices',
  full_name='AvailableServices',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='services', full_name='AvailableServices.services', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=64,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=73,
)


_NDARRAY = _descriptor.Descriptor(
  name='NDArray',
  full_name='NDArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ndarray', full_name='NDArray.ndarray', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=101,
)

DESCRIPTOR.message_types_by_name['AvailableServices'] = _AVAILABLESERVICES
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['NDArray'] = _NDARRAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AvailableServices = _reflection.GeneratedProtocolMessageType('AvailableServices', (_message.Message,), {
  'DESCRIPTOR' : _AVAILABLESERVICES,
  '__module__' : 'llsm_post_process_pb2'
  # @@protoc_insertion_point(class_scope:AvailableServices)
  })
_sym_db.RegisterMessage(AvailableServices)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'llsm_post_process_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

NDArray = _reflection.GeneratedProtocolMessageType('NDArray', (_message.Message,), {
  'DESCRIPTOR' : _NDARRAY,
  '__module__' : 'llsm_post_process_pb2'
  # @@protoc_insertion_point(class_scope:NDArray)
  })
_sym_db.RegisterMessage(NDArray)



_LLSMPOSTPROCESS = _descriptor.ServiceDescriptor(
  name='LLSMPostProcess',
  full_name='LLSMPostProcess',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=103,
  serialized_end=208,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetList',
    full_name='LLSMPostProcess.GetList',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_AVAILABLESERVICES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetZStackMaxIntensity',
    full_name='LLSMPostProcess.GetZStackMaxIntensity',
    index=1,
    containing_service=None,
    input_type=_NDARRAY,
    output_type=_NDARRAY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LLSMPOSTPROCESS)

DESCRIPTOR.services_by_name['LLSMPostProcess'] = _LLSMPOSTPROCESS

# @@protoc_insertion_point(module_scope)
