# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import llsm_post_process_pb2 as llsm__post__process__pb2


class LLSMPostProcessStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetList = channel.unary_unary(
                '/LLSMPostProcess/GetList',
                request_serializer=llsm__post__process__pb2.Empty.SerializeToString,
                response_deserializer=llsm__post__process__pb2.AvailableServices.FromString,
                )
        self.GetZStackMaxIntensity = channel.unary_unary(
                '/LLSMPostProcess/GetZStackMaxIntensity',
                request_serializer=llsm__post__process__pb2.NDArray.SerializeToString,
                response_deserializer=llsm__post__process__pb2.NDArray.FromString,
                )


class LLSMPostProcessServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetZStackMaxIntensity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LLSMPostProcessServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetList,
                    request_deserializer=llsm__post__process__pb2.Empty.FromString,
                    response_serializer=llsm__post__process__pb2.AvailableServices.SerializeToString,
            ),
            'GetZStackMaxIntensity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetZStackMaxIntensity,
                    request_deserializer=llsm__post__process__pb2.NDArray.FromString,
                    response_serializer=llsm__post__process__pb2.NDArray.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LLSMPostProcess', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LLSMPostProcess(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LLSMPostProcess/GetList',
            llsm__post__process__pb2.Empty.SerializeToString,
            llsm__post__process__pb2.AvailableServices.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetZStackMaxIntensity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LLSMPostProcess/GetZStackMaxIntensity',
            llsm__post__process__pb2.NDArray.SerializeToString,
            llsm__post__process__pb2.NDArray.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
